/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_.tables;


import com.cursojunit.paymentapi.models.entities.public_.Keys;
import com.cursojunit.paymentapi.models.entities.public_.Public;
import com.cursojunit.paymentapi.models.entities.public_.tables.records.PaymentRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Payment extends TableImpl<PaymentRecord> {

    private static final long serialVersionUID = -1784694736;

    /**
     * The reference instance of <code>PUBLIC.PAYMENT</code>
     */
    public static final Payment PAYMENT = new Payment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PaymentRecord> getRecordType() {
        return PaymentRecord.class;
    }

    /**
     * The column <code>PUBLIC.PAYMENT.PAYMENTID</code>.
     */
    public final TableField<PaymentRecord, Integer> PAYMENTID = createField("PAYMENTID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_445BABDE_EEED_4288_86FA_0116AE0A025B)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.PAYMENT.ORDERID</code>.
     */
    public final TableField<PaymentRecord, Integer> ORDERID = createField("ORDERID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PAYMENT.EVENTID</code>.
     */
    public final TableField<PaymentRecord, Integer> EVENTID = createField("EVENTID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PAYMENT.STATUS</code>.
     */
    public final TableField<PaymentRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.PAYMENT.TOTALAMOUNT</code>.
     */
    public final TableField<PaymentRecord, BigDecimal> TOTALAMOUNT = createField("TOTALAMOUNT", org.jooq.impl.SQLDataType.DECIMAL.precision(15, 2).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.PAYMENT</code> table reference
     */
    public Payment() {
        this("PAYMENT", null);
    }

    /**
     * Create an aliased <code>PUBLIC.PAYMENT</code> table reference
     */
    public Payment(String alias) {
        this(alias, PAYMENT);
    }

    private Payment(String alias, Table<PaymentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Payment(String alias, Table<PaymentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PaymentRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PAYMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Payment as(String alias) {
        return new Payment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Payment rename(String name) {
        return new Payment(name, null);
    }
}
