/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_.tables.records;


import com.cursojunit.paymentapi.models.entities.public_.tables.Allowedpaymentmethod;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllowedpaymentmethodRecord extends TableRecordImpl<AllowedpaymentmethodRecord> implements Record4<Integer, String, String, Boolean> {

    private static final long serialVersionUID = 1933583013;

    /**
     * Setter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.BRAND</code>.
     */
    public void setBrand(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.BRAND</code>.
     */
    public String getBrand() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.STATUS</code>.
     */
    public void setStatus(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.ALLOWEDPAYMENTMETHOD.STATUS</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD.BRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedpaymentmethodRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedpaymentmethodRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedpaymentmethodRecord value3(String value) {
        setBrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedpaymentmethodRecord value4(Boolean value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllowedpaymentmethodRecord values(Integer value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedpaymentmethodRecord
     */
    public AllowedpaymentmethodRecord() {
        super(Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD);
    }

    /**
     * Create a detached, initialised AllowedpaymentmethodRecord
     */
    public AllowedpaymentmethodRecord(Integer id, String name, String brand, Boolean status) {
        super(Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD);

        set(0, id);
        set(1, name);
        set(2, brand);
        set(3, status);
    }
}
