/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_.tables.records;


import com.cursojunit.paymentapi.models.entities.public_.tables.Paymentmethod;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentmethodRecord extends TableRecordImpl<PaymentmethodRecord> implements Record4<Integer, Integer, String, BigDecimal> {

    private static final long serialVersionUID = -465900936;

    /**
     * Setter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTMETHODID</code>.
     */
    public void setPaymentmethodid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTMETHODID</code>.
     */
    public Integer getPaymentmethodid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTID</code>.
     */
    public void setPaymentid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTID</code>.
     */
    public Integer getPaymentid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTMETHOD</code>.
     */
    public void setPaymentmethod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTMETHOD</code>.
     */
    public String getPaymentmethod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTAMOUNT</code>.
     */
    public void setPaymentamount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENTMETHOD.PAYMENTAMOUNT</code>.
     */
    public BigDecimal getPaymentamount() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Paymentmethod.PAYMENTMETHOD.PAYMENTMETHODID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Paymentmethod.PAYMENTMETHOD.PAYMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Paymentmethod.PAYMENTMETHOD.PAYMENTMETHOD_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Paymentmethod.PAYMENTMETHOD.PAYMENTAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPaymentmethodid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPaymentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPaymentmethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPaymentamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentmethodRecord value1(Integer value) {
        setPaymentmethodid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentmethodRecord value2(Integer value) {
        setPaymentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentmethodRecord value3(String value) {
        setPaymentmethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentmethodRecord value4(BigDecimal value) {
        setPaymentamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentmethodRecord values(Integer value1, Integer value2, String value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentmethodRecord
     */
    public PaymentmethodRecord() {
        super(Paymentmethod.PAYMENTMETHOD);
    }

    /**
     * Create a detached, initialised PaymentmethodRecord
     */
    public PaymentmethodRecord(Integer paymentmethodid, Integer paymentid, String paymentmethod, BigDecimal paymentamount) {
        super(Paymentmethod.PAYMENTMETHOD);

        set(0, paymentmethodid);
        set(1, paymentid);
        set(2, paymentmethod);
        set(3, paymentamount);
    }
}
