/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_.tables.records;


import com.cursojunit.paymentapi.models.entities.public_.tables.Payment;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends TableRecordImpl<PaymentRecord> implements Record5<Integer, Integer, Integer, String, BigDecimal> {

    private static final long serialVersionUID = 2129326910;

    /**
     * Setter for <code>PUBLIC.PAYMENT.PAYMENTID</code>.
     */
    public void setPaymentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT.PAYMENTID</code>.
     */
    public Integer getPaymentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT.ORDERID</code>.
     */
    public void setOrderid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT.ORDERID</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT.EVENTID</code>.
     */
    public void setEventid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT.EVENTID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT.STATUS</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.PAYMENT.TOTALAMOUNT</code>.
     */
    public void setTotalamount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.PAYMENT.TOTALAMOUNT</code>.
     */
    public BigDecimal getTotalamount() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, String, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Payment.PAYMENT.PAYMENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Payment.PAYMENT.ORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Payment.PAYMENT.EVENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Payment.PAYMENT.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Payment.PAYMENT.TOTALAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPaymentid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEventid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getTotalamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value1(Integer value) {
        setPaymentid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value2(Integer value) {
        setOrderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value3(Integer value) {
        setEventid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord value5(BigDecimal value) {
        setTotalamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentRecord values(Integer value1, Integer value2, Integer value3, String value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(Integer paymentid, Integer orderid, Integer eventid, String status, BigDecimal totalamount) {
        super(Payment.PAYMENT);

        set(0, paymentid);
        set(1, orderid);
        set(2, eventid);
        set(3, status);
        set(4, totalamount);
    }
}
