/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_;


import com.cursojunit.paymentapi.models.entities.public_.tables.Allowedpaymentmethod;
import com.cursojunit.paymentapi.models.entities.public_.tables.Payment;
import com.cursojunit.paymentapi.models.entities.public_.tables.Paymentmethod;
import com.cursojunit.paymentapi.models.entities.public_.tables.records.AllowedpaymentmethodRecord;
import com.cursojunit.paymentapi.models.entities.public_.tables.records.PaymentRecord;
import com.cursojunit.paymentapi.models.entities.public_.tables.records.PaymentmethodRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AllowedpaymentmethodRecord, Integer> IDENTITY_ALLOWEDPAYMENTMETHOD = Identities0.IDENTITY_ALLOWEDPAYMENTMETHOD;
    public static final Identity<PaymentRecord, Integer> IDENTITY_PAYMENT = Identities0.IDENTITY_PAYMENT;
    public static final Identity<PaymentmethodRecord, Integer> IDENTITY_PAYMENTMETHOD = Identities0.IDENTITY_PAYMENTMETHOD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AllowedpaymentmethodRecord, Integer> IDENTITY_ALLOWEDPAYMENTMETHOD = createIdentity(Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD, Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD.ID);
        public static Identity<PaymentRecord, Integer> IDENTITY_PAYMENT = createIdentity(Payment.PAYMENT, Payment.PAYMENT.PAYMENTID);
        public static Identity<PaymentmethodRecord, Integer> IDENTITY_PAYMENTMETHOD = createIdentity(Paymentmethod.PAYMENTMETHOD, Paymentmethod.PAYMENTMETHOD.PAYMENTMETHODID);
    }
}
