/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_;


import com.cursojunit.paymentapi.models.entities.DefaultCatalog;
import com.cursojunit.paymentapi.models.entities.public_.tables.Allowedpaymentmethod;
import com.cursojunit.paymentapi.models.entities.public_.tables.Payment;
import com.cursojunit.paymentapi.models.entities.public_.tables.Paymentmethod;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1746160961;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ALLOWEDPAYMENTMETHOD</code>.
     */
    public final Allowedpaymentmethod ALLOWEDPAYMENTMETHOD = com.cursojunit.paymentapi.models.entities.public_.tables.Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD;

    /**
     * The table <code>PUBLIC.PAYMENT</code>.
     */
    public final Payment PAYMENT = com.cursojunit.paymentapi.models.entities.public_.tables.Payment.PAYMENT;

    /**
     * The table <code>PUBLIC.PAYMENTMETHOD</code>.
     */
    public final Paymentmethod PAYMENTMETHOD = com.cursojunit.paymentapi.models.entities.public_.tables.Paymentmethod.PAYMENTMETHOD;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_445BABDE_EEED_4288_86FA_0116AE0A025B,
            Sequences.SYSTEM_SEQUENCE_4B3BDDBF_0A8C_4CEB_9B9D_64E84537F8C5,
            Sequences.SYSTEM_SEQUENCE_97CC4979_DF7A_4CA7_9343_C267339C0EFB);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD,
            Payment.PAYMENT,
            Paymentmethod.PAYMENTMETHOD);
    }
}
