/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_445BABDE_EEED_4288_86FA_0116AE0A025B</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_445BABDE_EEED_4288_86FA_0116AE0A025B = new SequenceImpl<Long>("SYSTEM_SEQUENCE_445BABDE_EEED_4288_86FA_0116AE0A025B", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_4B3BDDBF_0A8C_4CEB_9B9D_64E84537F8C5</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_4B3BDDBF_0A8C_4CEB_9B9D_64E84537F8C5 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_4B3BDDBF_0A8C_4CEB_9B9D_64E84537F8C5", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_97CC4979_DF7A_4CA7_9343_C267339C0EFB</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_97CC4979_DF7A_4CA7_9343_C267339C0EFB = new SequenceImpl<Long>("SYSTEM_SEQUENCE_97CC4979_DF7A_4CA7_9343_C267339C0EFB", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
