/*
 * This file is generated by jOOQ.
*/
package com.cursojunit.paymentapi.models.entities.public_;


import com.cursojunit.paymentapi.models.entities.public_.tables.Allowedpaymentmethod;
import com.cursojunit.paymentapi.models.entities.public_.tables.Payment;
import com.cursojunit.paymentapi.models.entities.public_.tables.Paymentmethod;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ALLOWEDPAYMENTMETHOD</code>.
     */
    public static final Allowedpaymentmethod ALLOWEDPAYMENTMETHOD = com.cursojunit.paymentapi.models.entities.public_.tables.Allowedpaymentmethod.ALLOWEDPAYMENTMETHOD;

    /**
     * The table <code>PUBLIC.PAYMENT</code>.
     */
    public static final Payment PAYMENT = com.cursojunit.paymentapi.models.entities.public_.tables.Payment.PAYMENT;

    /**
     * The table <code>PUBLIC.PAYMENTMETHOD</code>.
     */
    public static final Paymentmethod PAYMENTMETHOD = com.cursojunit.paymentapi.models.entities.public_.tables.Paymentmethod.PAYMENTMETHOD;
}
